spring:
  application:
    name: StoryLens
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
langchain4j:
  openai:
    chat-model:
      base-url: ${OPENAI_BASEURL}
      api-key: ${OPENAI_APIKEY}
      model-name: ${OPENAI_MODEL}
      log-requests: true
      log-responses: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
